set -g prefix ^A

set -g base-index 1

set -g renumber-windows on

set -g detach-on-destroy off

set-option -g mouse on

set-option -g status-position top

bind-key a set-window-option synchronize-panes\; display-message "synchronize-pane is now #{?pane_synchronized,on,off}"

bind-key C-i resize-pane -U 5
bind-key C-l resize-pane -R 5
bind-key C-k resize-pane -D 5
bind-key C-j resize-pane -L 5

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'tmux-plugins/tmux-continuum'

run '~/.tmux/plugins/tpm/tpm'
